#!/usr/bin/env python3
"""Regenerate <library>/index.md — the auto-maintained content catalog.

The index lists every page in the library grouped by section, with a
one-line summary. The output is deterministic — re-running on the same
state produces byte-identical output.

Sections (in order): Working Set, Memories (by category folder), Skills,
Context, Sources, Projects, Prompts.
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

import common


HEADER_PREFIX = "<!-- generated by /library:index — do not edit by hand -->"


def _summary_for_memory(path: Path) -> tuple[str, str]:
    """Return (title, summary) for a memory file."""
    try:
        text = path.read_text(encoding="utf-8")
        meta, body = common.parse_frontmatter(text)
    except (OSError, ValueError):
        return path.stem, ""
    title = str(meta.get("title", path.stem))
    # First non-empty, non-heading line of body.
    summary = ""
    for line in body.splitlines():
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        summary = s
        break
    if len(summary) > 120:
        summary = summary[:117] + "..."
    return title, summary


def _summary_for_skill(skill_md: Path) -> tuple[str, str]:
    try:
        text = skill_md.read_text(encoding="utf-8")
        meta, _ = common.parse_frontmatter(text)
    except (OSError, ValueError):
        return skill_md.parent.name, ""
    name = str(meta.get("name", skill_md.parent.name))
    description = str(meta.get("description", "")).strip()
    if len(description) > 120:
        description = description[:117] + "..."
    return name, description


def _first_heading(path: Path) -> str:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return path.stem
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("# "):
            return s[2:].strip()
    return path.stem


def _link(library: Path, target: Path) -> str:
    rel = target.relative_to(library)
    return rel.as_posix()


def _entry(label: str, link: str, summary: str) -> str:
    if summary:
        return f"- [{label}]({link}) — {summary}\n"
    return f"- [{label}]({link})\n"


def build_index(library: Path, *, now: datetime | None = None) -> str:
    now = now or datetime.now(timezone.utc)
    ts = now.strftime("%Y-%m-%dT%H:%M:%SZ")

    lines: list[str] = []
    lines.append(HEADER_PREFIX + "\n")
    lines.append(f"<!-- updated_at: {ts} -->\n\n")
    lines.append("# index\n\n")
    lines.append(
        "Content catalog for this AI context library. One entry per page,\n"
        "grouped by section. Auto-maintained by the plugin's PostToolUse\n"
        "hook and the `/library:index` command.\n\n"
    )

    # Working Set.
    lines.append("## Working Set\n\n")
    working_set_emitted = False
    for name in ("MEMORY.md", "USER.md", "CONSTRAINTS.md"):
        p = library / name
        if p.is_file():
            cap = common.HERMES_CAPS.get(name)
            body_len = common.body_char_count(p.read_text(encoding="utf-8"))
            summary = f"{body_len}/{cap} chars"
            lines.append(_entry(name, name, summary))
            working_set_emitted = True
    if not working_set_emitted:
        lines.append("(empty)\n")
    lines.append("\n")

    # Memories — grouped by subdirectory of memories/.
    lines.append("## Memories\n\n")
    mem_root = library / "memories"
    mem_emitted = False
    if mem_root.is_dir():
        for sub in sorted(p for p in mem_root.iterdir() if p.is_dir()):
            entries = sorted(sub.glob("*.md"))
            if not entries:
                continue
            mem_emitted = True
            lines.append(f"### {sub.name}\n\n")
            for path in entries:
                title, summary = _summary_for_memory(path)
                lines.append(_entry(title, _link(library, path), summary))
            lines.append("\n")
    if not mem_emitted:
        lines.append("(empty)\n\n")

    # Skills.
    lines.append("## Skills\n\n")
    sk_root = library / "skills"
    sk_emitted = False
    if sk_root.is_dir():
        for sub in sorted(p for p in sk_root.iterdir() if p.is_dir()):
            skill_md = sub / "SKILL.md"
            if not skill_md.is_file():
                continue
            sk_emitted = True
            name, summary = _summary_for_skill(skill_md)
            lines.append(_entry(name, _link(library, skill_md), summary))
    if not sk_emitted:
        lines.append("(empty)\n")
    lines.append("\n")

    # Context.
    lines.append("## Context\n\n")
    ctx_root = library / "context"
    ctx_emitted = False
    if ctx_root.is_dir():
        for path in sorted(ctx_root.glob("*.md")):
            ctx_emitted = True
            lines.append(_entry(_first_heading(path), _link(library, path), ""))
    if not ctx_emitted:
        lines.append("(empty)\n")
    lines.append("\n")

    # Sources.
    lines.append("## Sources\n\n")
    src_root = library / "sources"
    src_emitted = False
    if src_root.is_dir():
        for path in sorted(p for p in src_root.iterdir() if p.is_file()):
            src_emitted = True
            label = path.name
            lines.append(_entry(label, _link(library, path), ""))
    if not src_emitted:
        lines.append("(empty)\n")
    lines.append("\n")

    # Projects.
    lines.append("## Projects\n\n")
    proj_root = library / "projects"
    proj_emitted = False
    if proj_root.is_dir():
        for sub in sorted(p for p in proj_root.iterdir() if p.is_dir()):
            overview = sub / "overview.md"
            target = overview if overview.is_file() else sub
            label = _first_heading(overview) if overview.is_file() else sub.name
            lines.append(_entry(label, _link(library, target), ""))
            proj_emitted = True
    if not proj_emitted:
        lines.append("(empty)\n")
    lines.append("\n")

    # Prompts.
    lines.append("## Prompts\n\n")
    pr_root = library / "prompts"
    pr_emitted = False
    if pr_root.is_dir():
        for path in sorted(pr_root.glob("*.md")):
            pr_emitted = True
            lines.append(_entry(_first_heading(path), _link(library, path), ""))
    if not pr_emitted:
        lines.append("(empty)\n")
    lines.append("\n")

    return "".join(lines)


def regenerate(library: Path, *, now: datetime | None = None) -> Path:
    """Write the index to <library>/index.md. Returns the index path."""
    index_path = library / "index.md"
    text = build_index(library, now=now)
    index_path.write_text(text, encoding="utf-8")
    return index_path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate <library>/index.md.")
    parser.add_argument("library", nargs="?", default=None, help="Library root (defaults to $AI_CONTEXT_LIBRARY_PATH or cwd).")
    args = parser.parse_args(argv)

    try:
        library = common.resolve_library_path(args.library)
    except (FileNotFoundError, NotADirectoryError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    path = regenerate(library)
    print(f"regenerated: {path}")
    return 0


if __name__ == "__main__":
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    sys.exit(main())
